# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AristName', models.CharField(max_length=255)),
                ('AlbumTitle', models.CharField(max_length=255)),
                ('MyReview', models.TextField()),
                ('CoverURL', models.URLField()),
            ],
        ),
    ]
