# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistName', models.CharField(max_length=255)),
                ('SpotifyID', models.CharField(max_length=255)),
                ('PrimaryGenre', models.CharField(max_length=255)),
                ('SecondaryGenre', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Favorite_Album',
        ),
    ]
