# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_auto_20160316_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumTitle', models.CharField(max_length=255)),
                ('Favorite', models.IntegerField(default=0)),
                ('ArtsitName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.Artists')),
            ],
        ),
    ]
