# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0003_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='SpotifyAlbumID',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
