# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0005_auto_20160323_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumTitle', models.CharField(max_length=255)),
                ('SpotifyAlbumID', models.CharField(default=1, max_length=255)),
                ('Favorite', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='artists',
            name='id',
        ),
        migrations.AlterField(
            model_name='artists',
            name='SpotifyID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='album',
            name='ArtistID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.Artists'),
        ),
    ]
