# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0006_auto_20160323_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RealName', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.Album')),
                ('ArtistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.Artists')),
                ('ReviewerProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.Profile')),
            ],
        ),
    ]
