# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0007_profile_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.AlterField(
            model_name='album',
            name='SpotifyAlbumID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
