# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0008_auto_20160502_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
