# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0009_auto_20160502_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Review',
            field=models.TextField(default=''),
        ),
    ]
